<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Integration test">
<testcase name="compiler_tests/_example/example.c">
</testcase>
<testcase name="compiler_tests/array/declare_global.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_array_declare_global.linker.stderr.log and ./bin/output/compiler_tests_array_declare_global.linker.stdout.log">Fail: see ./bin/output/compiler_tests_array_declare_global.linker.stderr.log and ./bin/output/compiler_tests_array_declare_global.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/array/declare_local.c">
<error type="error" message="Fail: simulation did not exit with exit-code 0">Fail: simulation did not exit with exit-code 0</error>
</testcase>
<testcase name="compiler_tests/array/index_constant.c">
<error type="error" message="Fail: simulation did not exit with exit-code 0">Fail: simulation did not exit with exit-code 0</error>
</testcase>
<testcase name="compiler_tests/array/index_expression.c">
<error type="error" message="Fail: simulation did not exit with exit-code 0">Fail: simulation did not exit with exit-code 0</error>
</testcase>
<testcase name="compiler_tests/array/index_variable.c">
<error type="error" message="Fail: simulation did not exit with exit-code 0">Fail: simulation did not exit with exit-code 0</error>
</testcase>
<testcase name="compiler_tests/control_flow/for_multiple.c">
<error type="error" message="Fail: simulation did not exit with exit-code 0">Fail: simulation did not exit with exit-code 0</error>
</testcase>
<testcase name="compiler_tests/control_flow/for_one.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_control_flow_for_one.compiler.stderr.log and ./bin/output/compiler_tests_control_flow_for_one.compiler.stdout.log">Fail: see ./bin/output/compiler_tests_control_flow_for_one.compiler.stderr.log and ./bin/output/compiler_tests_control_flow_for_one.compiler.stdout.log</error>
</testcase>
<testcase name="compiler_tests/control_flow/for_zero_v1.c">
<error type="error" message="Fail: simulation did not exit with exit-code 0">Fail: simulation did not exit with exit-code 0</error>
</testcase>
<testcase name="compiler_tests/control_flow/for_zero_v2.c">
<error type="error" message="Fail: simulation did not exit with exit-code 0">Fail: simulation did not exit with exit-code 0</error>
</testcase>
<testcase name="compiler_tests/control_flow/if_else_false.c">
<error type="error" message="Fail: simulation did not exit with exit-code 0">Fail: simulation did not exit with exit-code 0</error>
</testcase>
<testcase name="compiler_tests/control_flow/if_else_true.c">
<error type="error" message="Fail: simulation did not exit with exit-code 0">Fail: simulation did not exit with exit-code 0</error>
</testcase>
<testcase name="compiler_tests/control_flow/if_false.c">
<error type="error" message="Fail: simulation did not exit with exit-code 0">Fail: simulation did not exit with exit-code 0</error>
</testcase>
<testcase name="compiler_tests/control_flow/if_true.c">
<error type="error" message="Fail: simulation did not exit with exit-code 0">Fail: simulation did not exit with exit-code 0</error>
</testcase>
<testcase name="compiler_tests/control_flow/sequence.c">
<error type="error" message="Fail: simulation did not exit with exit-code 0">Fail: simulation did not exit with exit-code 0</error>
</testcase>
<testcase name="compiler_tests/control_flow/while_multiple.c">
<error type="error" message="Fail: simulation did not exit with exit-code 0">Fail: simulation did not exit with exit-code 0</error>
</testcase>
<testcase name="compiler_tests/control_flow/while_once.c">
<error type="error" message="Fail: simulation did not exit with exit-code 0">Fail: simulation did not exit with exit-code 0</error>
</testcase>
<testcase name="compiler_tests/control_flow/while_zero.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_control_flow_while_zero.compiler.stderr.log and ./bin/output/compiler_tests_control_flow_while_zero.compiler.stdout.log">Fail: see ./bin/output/compiler_tests_control_flow_while_zero.compiler.stderr.log and ./bin/output/compiler_tests_control_flow_while_zero.compiler.stdout.log</error>
</testcase>
<testcase name="compiler_tests/default/test_ADD0.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_default_test_ADD0.assembler.stderr.log and ./bin/output/compiler_tests_default_test_ADD0.assembler.stdout.log">Fail: see ./bin/output/compiler_tests_default_test_ADD0.assembler.stderr.log and ./bin/output/compiler_tests_default_test_ADD0.assembler.stdout.log</error>
</testcase>
<testcase name="compiler_tests/default/test_ADD1.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_default_test_ADD1.assembler.stderr.log and ./bin/output/compiler_tests_default_test_ADD1.assembler.stdout.log">Fail: see ./bin/output/compiler_tests_default_test_ADD1.assembler.stderr.log and ./bin/output/compiler_tests_default_test_ADD1.assembler.stdout.log</error>
</testcase>
<testcase name="compiler_tests/default/test_CALL.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_default_test_CALL.linker.stderr.log and ./bin/output/compiler_tests_default_test_CALL.linker.stdout.log">Fail: see ./bin/output/compiler_tests_default_test_CALL.linker.stderr.log and ./bin/output/compiler_tests_default_test_CALL.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/default/test_LOCAL.c">
<error type="error" message="Fail: simulation did not exit with exit-code 0">Fail: simulation did not exit with exit-code 0</error>
</testcase>
<testcase name="compiler_tests/default/test_RETURN.c">
</testcase>
<testcase name="compiler_tests/float/add_double.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_float_add_double.assembler.stderr.log and ./bin/output/compiler_tests_float_add_double.assembler.stdout.log">Fail: see ./bin/output/compiler_tests_float_add_double.assembler.stderr.log and ./bin/output/compiler_tests_float_add_double.assembler.stdout.log</error>
</testcase>
<testcase name="compiler_tests/float/add.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_float_add.assembler.stderr.log and ./bin/output/compiler_tests_float_add.assembler.stdout.log">Fail: see ./bin/output/compiler_tests_float_add.assembler.stderr.log and ./bin/output/compiler_tests_float_add.assembler.stdout.log</error>
</testcase>
<testcase name="compiler_tests/float/add_mul.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_float_add_mul.assembler.stderr.log and ./bin/output/compiler_tests_float_add_mul.assembler.stdout.log">Fail: see ./bin/output/compiler_tests_float_add_mul.assembler.stderr.log and ./bin/output/compiler_tests_float_add_mul.assembler.stdout.log</error>
</testcase>
<testcase name="compiler_tests/float/mul_add.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_float_mul_add.assembler.stderr.log and ./bin/output/compiler_tests_float_mul_add.assembler.stdout.log">Fail: see ./bin/output/compiler_tests_float_mul_add.assembler.stderr.log and ./bin/output/compiler_tests_float_mul_add.assembler.stdout.log</error>
</testcase>
<testcase name="compiler_tests/float/mul_double.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_float_mul_double.linker.stderr.log and ./bin/output/compiler_tests_float_mul_double.linker.stdout.log">Fail: see ./bin/output/compiler_tests_float_mul_double.linker.stderr.log and ./bin/output/compiler_tests_float_mul_double.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/float/mul.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_float_mul.linker.stderr.log and ./bin/output/compiler_tests_float_mul.linker.stdout.log">Fail: see ./bin/output/compiler_tests_float_mul.linker.stderr.log and ./bin/output/compiler_tests_float_mul.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/float/pow.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_float_pow.compiler.stderr.log and ./bin/output/compiler_tests_float_pow.compiler.stdout.log">Fail: see ./bin/output/compiler_tests_float_pow.compiler.stderr.log and ./bin/output/compiler_tests_float_pow.compiler.stdout.log</error>
</testcase>
<testcase name="compiler_tests/functions/call_constant_external.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_functions_call_constant_external.linker.stderr.log and ./bin/output/compiler_tests_functions_call_constant_external.linker.stdout.log">Fail: see ./bin/output/compiler_tests_functions_call_constant_external.linker.stderr.log and ./bin/output/compiler_tests_functions_call_constant_external.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/functions/call_constant_internal.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_functions_call_constant_internal.linker.stderr.log and ./bin/output/compiler_tests_functions_call_constant_internal.linker.stdout.log">Fail: see ./bin/output/compiler_tests_functions_call_constant_internal.linker.stderr.log and ./bin/output/compiler_tests_functions_call_constant_internal.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/functions/call_five_args_external.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_functions_call_five_args_external.linker.stderr.log and ./bin/output/compiler_tests_functions_call_five_args_external.linker.stdout.log">Fail: see ./bin/output/compiler_tests_functions_call_five_args_external.linker.stderr.log and ./bin/output/compiler_tests_functions_call_five_args_external.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/functions/call_five_args_internal.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_functions_call_five_args_internal.assembler.stderr.log and ./bin/output/compiler_tests_functions_call_five_args_internal.assembler.stdout.log">Fail: see ./bin/output/compiler_tests_functions_call_five_args_internal.assembler.stderr.log and ./bin/output/compiler_tests_functions_call_five_args_internal.assembler.stdout.log</error>
</testcase>
<testcase name="compiler_tests/functions/call_identity_external.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_functions_call_identity_external.linker.stderr.log and ./bin/output/compiler_tests_functions_call_identity_external.linker.stdout.log">Fail: see ./bin/output/compiler_tests_functions_call_identity_external.linker.stderr.log and ./bin/output/compiler_tests_functions_call_identity_external.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/functions/call_identity_internal.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_functions_call_identity_internal.assembler.stderr.log and ./bin/output/compiler_tests_functions_call_identity_internal.assembler.stdout.log">Fail: see ./bin/output/compiler_tests_functions_call_identity_internal.assembler.stderr.log and ./bin/output/compiler_tests_functions_call_identity_internal.assembler.stdout.log</error>
</testcase>
<testcase name="compiler_tests/functions/call_mutual_recursive.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_functions_call_mutual_recursive.linker.stderr.log and ./bin/output/compiler_tests_functions_call_mutual_recursive.linker.stdout.log">Fail: see ./bin/output/compiler_tests_functions_call_mutual_recursive.linker.stderr.log and ./bin/output/compiler_tests_functions_call_mutual_recursive.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/functions/call_recursive_internal.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_functions_call_recursive_internal.linker.stderr.log and ./bin/output/compiler_tests_functions_call_recursive_internal.linker.stdout.log">Fail: see ./bin/output/compiler_tests_functions_call_recursive_internal.linker.stderr.log and ./bin/output/compiler_tests_functions_call_recursive_internal.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/functions/call_two_args_external.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_functions_call_two_args_external.linker.stderr.log and ./bin/output/compiler_tests_functions_call_two_args_external.linker.stdout.log">Fail: see ./bin/output/compiler_tests_functions_call_two_args_external.linker.stderr.log and ./bin/output/compiler_tests_functions_call_two_args_external.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/functions/call_two_args_internal.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_functions_call_two_args_internal.assembler.stderr.log and ./bin/output/compiler_tests_functions_call_two_args_internal.assembler.stdout.log">Fail: see ./bin/output/compiler_tests_functions_call_two_args_internal.assembler.stderr.log and ./bin/output/compiler_tests_functions_call_two_args_internal.assembler.stdout.log</error>
</testcase>
<testcase name="compiler_tests/integer/add.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_integer_add.assembler.stderr.log and ./bin/output/compiler_tests_integer_add.assembler.stdout.log">Fail: see ./bin/output/compiler_tests_integer_add.assembler.stderr.log and ./bin/output/compiler_tests_integer_add.assembler.stdout.log</error>
</testcase>
<testcase name="compiler_tests/integer/bitwise_and.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_integer_bitwise_and.linker.stderr.log and ./bin/output/compiler_tests_integer_bitwise_and.linker.stdout.log">Fail: see ./bin/output/compiler_tests_integer_bitwise_and.linker.stderr.log and ./bin/output/compiler_tests_integer_bitwise_and.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/integer/bitwise_or.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_integer_bitwise_or.linker.stderr.log and ./bin/output/compiler_tests_integer_bitwise_or.linker.stdout.log">Fail: see ./bin/output/compiler_tests_integer_bitwise_or.linker.stderr.log and ./bin/output/compiler_tests_integer_bitwise_or.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/integer/bitwise_xor.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_integer_bitwise_xor.linker.stderr.log and ./bin/output/compiler_tests_integer_bitwise_xor.linker.stdout.log">Fail: see ./bin/output/compiler_tests_integer_bitwise_xor.linker.stderr.log and ./bin/output/compiler_tests_integer_bitwise_xor.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/integer/div.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_integer_div.linker.stderr.log and ./bin/output/compiler_tests_integer_div.linker.stdout.log">Fail: see ./bin/output/compiler_tests_integer_div.linker.stderr.log and ./bin/output/compiler_tests_integer_div.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/integer/equal.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_integer_equal.linker.stderr.log and ./bin/output/compiler_tests_integer_equal.linker.stdout.log">Fail: see ./bin/output/compiler_tests_integer_equal.linker.stderr.log and ./bin/output/compiler_tests_integer_equal.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/integer/less_than.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_integer_less_than.linker.stderr.log and ./bin/output/compiler_tests_integer_less_than.linker.stdout.log">Fail: see ./bin/output/compiler_tests_integer_less_than.linker.stderr.log and ./bin/output/compiler_tests_integer_less_than.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/integer/less_than_equal.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_integer_less_than_equal.linker.stderr.log and ./bin/output/compiler_tests_integer_less_than_equal.linker.stdout.log">Fail: see ./bin/output/compiler_tests_integer_less_than_equal.linker.stderr.log and ./bin/output/compiler_tests_integer_less_than_equal.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/integer/logical_and.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_integer_logical_and.linker.stderr.log and ./bin/output/compiler_tests_integer_logical_and.linker.stdout.log">Fail: see ./bin/output/compiler_tests_integer_logical_and.linker.stderr.log and ./bin/output/compiler_tests_integer_logical_and.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/integer/logical_or.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_integer_logical_or.linker.stderr.log and ./bin/output/compiler_tests_integer_logical_or.linker.stdout.log">Fail: see ./bin/output/compiler_tests_integer_logical_or.linker.stderr.log and ./bin/output/compiler_tests_integer_logical_or.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/integer/mul.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_integer_mul.linker.stderr.log and ./bin/output/compiler_tests_integer_mul.linker.stdout.log">Fail: see ./bin/output/compiler_tests_integer_mul.linker.stderr.log and ./bin/output/compiler_tests_integer_mul.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/integer/sub.c">
<error type="error" message="Fail: see ./bin/output/compiler_tests_integer_sub.linker.stderr.log and ./bin/output/compiler_tests_integer_sub.linker.stdout.log">Fail: see ./bin/output/compiler_tests_integer_sub.linker.stderr.log and ./bin/output/compiler_tests_integer_sub.linker.stdout.log</error>
</testcase>
<testcase name="compiler_tests/local_var/constant_initialiser.c">
<error type="error" message="Fail: simulation did not exit with exit-code 0">Fail: simulation did not exit with exit-code 0</error>
</testcase>
<testcase name="compiler_tests/local_var/dual_var.c">
